### ISSUE TITLE
High goal vision

### ISSUE THREAD

**Issue by leinad2018** [2202Programming/Tim.JAR#49]
Vision to sense the high goal

**Comment by noahmayeshiba** [comment]
Jaluo did this, he did a good job, it seems to work.

**Comment by jialuogao** [comment]
Wait. What does # 49 mean?

**Comment by tomlazar** [comment]
its just a id pr's and issues share a number which is used to differentiate them.

**Comment by SecondThread** [comment]
We still have to finish this by getting the servo to turn when the high goal vision tells it to
