### ISSUE TITLE
Hoenheim Shooter system

### ISSUE THREAD

**Issue by leinad2018** [2202Programming/Tim.JAR#66]
We need to recreate hoenheim so that it can shoot just like it used to. We have the cpp code to look back on, but this will be a lot of work.

**Comment by tomlazar** [comment]
[Here](https://github.com/2202Programming/2014/blob/master/Hoemhien(2014)/ShooterControl.cpp) is the old cpp code from 2014. 

At first glance, it is a lot of code (_over 600 lines_) but the core of it several state machines. Two mainly.

- [ ] Ball Grabber
- [ ] Shooter

Between these two the Shooter will be harder and will require a PID control.
